### PR TITLE
Add Windows support

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by rnorth** [comment]
Thanks - this looks sensible. Will merge.

**Comment by seanf** [comment]
@rnorth Did you mean to close without merging? Should I leave this branch open?

**Comment by rnorth** [comment]
Yikes! Completely did not mean to do that!

## Sorry, will merge shortly.

Richard

**Comment by rnorth** [comment]
Done - sorry about that!

**Comment by seanf** [comment]
Thanks @rnorth . I'm hoping you've got some inspiration for #4 , because having Docker work more easily on Windows than on Linux is too weird.

**Pull request merged**
